name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          USERNAME: ${{ secrets.DeployUsername }}
          PASSWORD: ${{ secrets.DeployPassword }}
        run: |
          curl --user "$USERNAME:$PASSWORD" https://vigrid.velvetcache.org/deploy/new

