name: JavaScript Tests
on: [push]

jobs:
  test-golang:
    runs-on: ubuntu-latest
    defaults:
        working-directory: poller/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '20.x'
      - run: go mod download
      - run: go test -v ./...
  test-javascript:
    runs-on: ubuntu-latest
    defaults:
        working-directory: web/
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test

